language: node_js

before_install:
- sudo apt-get -y install openssh-client ttf-freefont
- openssl aes-256-cbc -K $encrypted_77965d5bdd4d_key -iv $encrypted_77965d5bdd4d_iv
  -in deploy_key.enc -out ./deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
- ssh -i deploy_key root@naumann.hosting pwd
- nvm install --lts
- npm install -g @ionic/cli
- git clone https://github.com/x3kcl/suhr.git
addons:
  apt:
    update: true
  ssh_known_hosts: naumann.hosting
before_script:
- google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost
  &
script:
- ionic build --prod --engine=browser --watch=false --release
- tar cjvf www.tar.bz www

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/www root@naumann.hosting:/root/www
  on:
    branch: master