language: node_js
before_install:
- openssl aes-256-cbc -K $encrypted_edc15e6e3ccc_key -iv $encrypted_edc15e6e3ccc_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- sudo apt-get -y install chromium-browser ttf-freefont firefox
- nvm install --lts
- npm install -g @ionic/cli
- git clone https://github.com/x3kcl/suhr.git
addons:
  apt:
    update: true
  ssh_known_hosts: naumann.hosting
before_script:
- 
- google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost
  &
script:
- ionic build --prod --engine=browser --watch=false --release
- tar cjvf www.tar.bz www
before_deploy:
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/www root@naumann.hosting:/root/www
  on:
    branch: master