language: node_js

before_install:
- sudo apt-get -y install openssh-client
- git clone https://github.com/x3kcl/suhr.git
- openssl aes-256-cbc -K $encrypted_77965d5bdd4d_key -iv $encrypted_77965d5bdd4d_iv
  -in $TRAVIS_BUILD_DIR/deploy_rsa.enc -out $TRAVIS_BUILD_DIR/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 $TRAVIS_BUILD_DIR/deploy_rsa
- echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add $TRAVIS_BUILD_DIR/deploy_rsa
- ssh -i $TRAVIS_BUILD_DIR/deploy_rsa root@naumann.hosting pwd
- nvm install --lts
- npm install -g @ionic/cli
addons:
  apt:
    update: true
  ssh_known_hosts: naumann.hosting
before_script:
- google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost
  &
script:
- ionic build --prod --engine=browser --watch=false --release
- tar cjvf www.tar.bz www

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/www root@naumann.hosting:/root/www
  on:
    branch: master