language: node_js

before_install:
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.2/install.sh | bash
  - npm install -g @ionic/cli
  - git clone https://github.com/x3kcl/suhr.git
  - npm install

install:
  - ionic build --prod
