language: node_js
before_install:
- openssl aes-256-cbc -K $encrypted_edc15e6e3ccc_key -iv $encrypted_edc15e6e3ccc_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- sudo apt-get -y install chromium-browser ttf-freefont firefox
- nvm install --lts
- npm install -g @ionic/cli
- git clone https://github.com/x3kcl/suhr.git
addons:
  apt:
    update: true
before_script:
- 
- google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost
  &
script:
- ionic build --prod --engine=browser --watch=false --release
- tar cjvf www.tar.bz www
