language: node_js

before_install:
  - sudo apt-get -y install chromium-browser ttf-freefont firefox
  - nvm install --lts
  - npm install -g @ionic/cli
  - git clone https://github.com/x3kcl/suhr.git
addons:
  apt:
    update: true

services:
  - xvfb

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  
script:
  - ionic build --prod --engine=browser --watch=false --release
  - tar cjvf www.tar.bz www
