language: node_js

before_install:
  - sudo apt-get -y install chromium-browser ttf-freefont firefox
  - nvm install --lts
  - npm install -g @ionic/cli
  - git clone https://github.com/x3kcl/suhr.git
addons:
  apt:
    update: true

services:
  - xvfb

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - ionic build --prod --engine=browser --watch=false --release
  - tar cjvf www.tar.bz www
